name: CICD

on: 
    push:
        branches: [ "main" ]

jobs: 
    build:

        runs-on: ubuntu-latest
        
        steps:
            - run: echo "Start build process"

            - name: Checkout
              uses: actions/checkout@v4.2.2

            - name: check code and install dependencies
              run: |
                    ls
                    node -v
                    npm ci

            - name: build
              run: |
                    npm run build
                    ls

    deploy:

        runs-on: ubuntu-latest

        needs: build
        
        steps:

            - run: ls
            